import NavBar from "@/global/components/NavBar";
import Head from "next/head";
import * as M from "@mui/material";
import * as S from "./styles";
import { useRouter } from "next/router"

export default function Home() {
  const { push } = useRouter()

  return (
    <S.Container>
      <Head>
        <title>One Piece | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <div className="container">
        <M.Typography variant="h3" component="h2" sx={{ color: "white", textAlign: 'center', marginBottom: 2 }}>
          Bem-vindo ao maravilhoso mundo de One Piece
        </M.Typography>
        <M.Typography variant="h6" component="h2" sx={{ color: "white", textAlign: 'center' }}>
          É a era dos piratas! Luffy, um garoto travesso, sonha em se tornar
          torne-se o rei dos piratas encontrando One Piece, um fabuloso e
          tesouro misterioso. Mas, inadvertidamente, um dia Luffy engoliu um
          A fruta do diabo mágica que o transformou em um homem de borracha. Desde
          então, ele consegue contorcer seu corpo elástico em todas as direções,
          mas perdeu a habilidade de nadar, a altura de um pirata! Junto
          mais e mais aventuras incríveis e encontros casuais, Luffy vai para o
          poucos compondo sua tripulação e multiplicando amizades com os povos que
          descubra, enquanto enfrenta inimigos formidáveis.
        </M.Typography>

        <S.Box>
          <M.Button variant="contained"
            sx={{
              ml: 1,
              "&.MuiButtonBase-root:hover": {
                bgcolor: "transparent"
              }
            }}
            onClick={() => push('/characters')}
          >
            Todos os Personagens
          </M.Button>
        </S.Box>
      </div>
    </S.Container>
  );
}