import axios from 'axios';
import Head from 'next/head'
import { SetStateAction, useEffect, useState } from 'react';

export default function Home() {
  const [data, setData] = useState();
  const baseURL = `https://one-piece-br-default-rtdb.firebaseio.com/characters.json`;

  useEffect(() => {
    axios
      .get(baseURL)
      .then((response) => setData(response.data))
      .catch(function (error: { toJSON: () => any; }) {
        console.log(error.toJSON());
      });
  }, [baseURL]);

  console.log(data, 'data');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data &&
        Object.values(data).map((item: any) => {
          return <p>{item.name}</p>
        })}
    </>
  )
}
