import axios from "axios";
import { useRouter } from "next/router";
import React, { Fragment, useEffect, useState } from "react";
import Head from "next/head";
import NavBar from "@/global/components/NavBar";
import CardInfos from "@/global/components/CardInfos";
import RecipeReviewCard from "@/global/components/CardInfos/card";

export default function Description() {
  const [data, setData] = useState<any>([]);
  const [open, setOpen] = React.useState(false);

  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    axios
      .get(
        `https://one-piece-br-default-rtdb.firebaseio.com/characters/${id}.json/`,
        {
          headers: {},
        }
      )
      .then((response: { data: any }) => {
        //console.log(response, "description");
        setData(response.data);
      })
      .catch(function (error: { toJSON: () => any }) {
        console.log(error.toJSON());
      });
  }, [id]);
  //console.log(data, "data description");
  return (
    <Fragment>
      <Head>
        <title>One Piece | Descriptions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar isBack />
      <Fragment >
        <RecipeReviewCard data={data} open={open} handleClose={handleClose} handleOpen={handleOpen} />
      </Fragment>
    </Fragment>
  );
}
