import axios from "axios";
import { useRouter } from "next/router";
import { Fragment, useEffect, useState } from "react";
import * as M from "@mui/material";
import Head from "next/head";

export default function Description() {
  const [data, setData] = useState();
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
      axios
        .get(`https://one-piece-br-default-rtdb.firebaseio.com/characters.json?id=${id}`,
        {
          headers: {},
        }
      )
        .then((response: { data: any }) => {
          setData(response.data);
        })
        .catch(function (error: { toJSON: () => any }) {
          console.log(error.toJSON());
        });
  }, [id]);

  console.log(data, 'description');
  
 
  return (   
    <Fragment>
     <Head>
        <title>One Piece | Descriptions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {data &&
      Object.values(data).map((item: any, index: any) => {
        return (
      // eslint-disable-next-line react/jsx-key
      <p>
        {item.name}
      </p>
        );
      })}      
  </Fragment>
  )
}
