import React, { Fragment } from "react";
import Head from "next/head";
import NavBar from "@/global/components/NavBar";
import CardInfos from "@/global/components/CardInfos";
import { useOnePiece } from "@/global/Provider/contextAll";

export default function Description() {
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  const {resposta} = useOnePiece()

  console.log(resposta, 'descrition');
  

  return (
    <Fragment>
      <Head>
        <title>One Piece | {resposta?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar isBack />
      <Fragment >
        <CardInfos data={resposta} open={open} handleClose={handleClose} handleOpen={handleOpen} />
      </Fragment>
    </Fragment>
  );
}
